version: '3'
services:
  redis:
    container_name: redis-server
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6779:6379'
      - '8001:8001'
  node:
    container_name: node-server
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules 
    depends_on:
      - redis